version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: go run main.go
    volumes:
      - .:/go/src/rosella
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - ./clone_testing_db.sh:/usr/bin/clone_testing_db
